In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('States_Lat_Long.csv')

In [3]:
df

,Unnamed: 0,USAState,TotalCases,NewCases,TotalDeaths,NewDeaths,ActiveCases,Source
0,0,New York,20875,"+5,085",157.0,43.0,20610,[source] [source] [source] [source] [source] [...
1,1,New Jersey,2844,+930,27.0,7.0,2817,[source] [source]
2,2,Washington,2221,+225,110.0,15.0,1987,[source]
3,3,California,2133,+378,40.0,6.0,2087,[source] [source] [source]
4,4,Michigan,1328,+293,15.0,6.0,1313,[source] [source] [source]
5,5,Illinois,1285,+236,12.0,3.0,1271,[source]
6,6,Florida,1227,+220,18.0,5.0,1209,[source] [source]
7,7,Louisiana,1172,+335,35.0,15.0,1137,[source] [source]
8,8,Texas,806,+208,9.0,3.0,786,[source] [source] [source] [source] [source]
9,9,Georgia,800,+200,26.0,3.0,774,[source]
10,10,Massachusetts,777,+131,9.0,4.0,767,[source] [source]
11,11,Colorado,720,+129,7.0,1.0,713,[source] [source] [source]
12,12,Pennsylvania,644,+165,6.0,3.0,638,[source] [source]
13,13,Tennessee,615,+110,2.0,NaN,613,[source] [source] [source]
14,14,Ohio,442,+91,6.0,3.0,436,[source]
15,15,Wisconsin,416,+35,5.0,1.0,410,[source]
16,16,Connecticut,415,+192,10.0,5.0,405,[source] [source] [source]
17,17,North Carolina,410,+139,NaN,NaN,410,[source] [source]
18,18,South Carolina,299,+104,5.0,2.0,294,[source]
19,19,Maryland,288,+44,3.0,NaN,281,[source]
20,20,Indiana,259,+58,7.0,1.0,252,[source]
21,21,Utah,257,+76,1.0,NaN,256,[source]
22,22,Virginia,254,+35,7.0,4.0,246,[source] [source]
23,23,Mississippi,249,+42,1.0,NaN,248,[source]
24,24,Nevada,245,+55,4.0,2.0,241,[source]
25,25,Minnesota,235,+66,1.0,NaN,210,[source]
26,26,Arizona,234,+82,2.0,NaN,231,[source]
27,27,Arkansas,197,+32,NaN,NaN,197,[source] [source]
28,28,Alabama,196,+39,NaN,NaN,196,[source]
29,29,Oregon,191,+30,5.0,1.0,186,[source] [source]
30,30,Missouri,183,+93,4.0,1.0,179,[source] [source]
31,31,District of Columbia,137,+39,2.0,NaN,135,[source]
32,32,Kentucky,124,+21,4.0,1.0,118,[source] [source]
33,33,Maine,107,+18,NaN,NaN,104,[source]
34,34,Rhode Island,106,+23,NaN,NaN,106,[source] [source]
35,35,Iowa,105,+15,NaN,NaN,105,[source] [source]
36,36,New Hampshire,101,+23,1.0,1.0,100,[source] [source]
37,37,New Mexico,83,+18,NaN,NaN,83,[source]
38,38,Kansas,82,+18,2.0,NaN,80,[source] [source] [source]
39,39,Oklahoma,81,+14,2.0,NaN,78,[source]
40,40,Hawaii,77,+21,NaN,NaN,77,[source]
41,41,Vermont,75,+23,5.0,3.0,70,[source]
42,42,Delaware,68,+12,NaN,NaN,68,[source]
43,43,Nebraska,50,+8,NaN,NaN,50,[source]
44,44,Idaho,47,+5,NaN,NaN,47,[source]
45,45,Montana,45,+11,NaN,NaN,45,[source]
46,46,Alaska,32,+10,NaN,NaN,32,[source] [source]
47,47,North Dakota,32,+2,NaN,NaN,32,[source]
48,48,South Dakota,28,+7,1.0,NaN,21,[source]
49,49,Wyoming,26,+2,NaN,NaN,26,[source]
50,50,West Virginia,16,+4,NaN,NaN,16,[source] [source]
51,51,Diamond Princess Cruise,49,NaN,NaN,NaN,49,NaN
52,52,Grand Princess Cruise,30,NaN,1.0,NaN,29,NaN
53,53,Total:,43718,10152,552.0,139.0,42871,NaN

In [4]:
df1 = pd.read_csv('Lat_Long_data.csv')

In [5]:
df1[['Lat', 'Lng']] = df1.latlng.str.split(",", expand = True)

In [6]:
df1.drop(columns = ['latlng'], inplace = True)

In [7]:
df1 = df1.rename(columns = {'state':'USAState'})

In [8]:
df1

                USAState        Lat          Lng
0               New York  40.663468   -73.938697
1             California  34.019394  -118.410825
2               Illinois  41.837551   -87.681844
3                  Texas  29.786642   -95.390899
4                Arizona  33.572154  -112.090132
5           Pennsylvania  40.009376   -75.133346
6                Florida  30.336864   -81.661603
7         North Carolina  35.208707   -80.830739
8                   Ohio  39.984371   -82.984787
9                Indiana  39.776664   -86.145935
10            Washington  47.619349  -122.351471
11              Colorado   39.76185  -104.881105
12  District of Columbia  38.904103   -77.017229
13         Massachusetts  42.338551   -71.018253
14             Tennessee    36.1718   -86.785002
15                Oregon  45.536951  -122.649971
16                Nevada  36.227551  -115.263782
17              Oklahoma  35.467079   -97.513657
18              Michigan  42.383037   -83.102237
19              Kentucky  38.165376   -85.647377
20              Maryland  39.300032   -76.610476
21             Wisconsin  43.063348   -87.966695
22            New Mexico   35.10478  -106.646809
23               Georgia  33.762909   -84.422675
24              Missouri  39.125129   -94.551028
25              Virginia  36.779985   -76.025209
26              Nebraska  41.261748   -96.047142
27             Minnesota  44.963324    -93.26832
28             Louisiana   30.05342   -89.934502
29                Kansas  37.690638   -97.345836
30                Hawaii  21.324347   -157.84764
31                Alaska   61.17425  -149.284329
32            New Jersey   40.72422   -74.172574
33                 Idaho  43.600229  -116.231656
34                  Iowa   41.57259   -93.610243
35               Alabama  33.527444   -86.799047
36                  Utah  40.776928  -111.930991
37              Arkansas  34.725432   -92.358556
38          South Dakota  43.539466   -96.732035
39          Rhode Island  41.823056   -71.418784
40           Mississippi  32.315831   -90.212823
41        South Carolina   32.81793    -79.95896
42           Connecticut  41.187393   -73.195757

In [9]:
df_final = df.merge(df1, how = 'outer', on = 'USAState' )

In [10]:
df_final.columns

Index(['Unnamed: 0', 'USAState', 'TotalCases', 'NewCases', 'TotalDeaths',
       'NewDeaths', 'ActiveCases', 'Source', 'Lat', 'Lng'],
      dtype='object')

In [11]:
df_final = df_final.drop(columns = ['Unnamed: 0','Source'])

In [12]:
df_final

,USAState,TotalCases,NewCases,TotalDeaths,NewDeaths,ActiveCases,Lat,Lng
0,New York,20875,"+5,085",157.0,43.0,20610,40.663468,-73.938697
1,New Jersey,2844,+930,27.0,7.0,2817,40.72422,-74.172574
2,Washington,2221,+225,110.0,15.0,1987,47.619349,-122.351471
3,California,2133,+378,40.0,6.0,2087,34.019394,-118.410825
4,Michigan,1328,+293,15.0,6.0,1313,42.383037,-83.102237
5,Illinois,1285,+236,12.0,3.0,1271,41.837551,-87.681844
6,Florida,1227,+220,18.0,5.0,1209,30.336864,-81.661603
7,Louisiana,1172,+335,35.0,15.0,1137,30.05342,-89.934502
8,Texas,806,+208,9.0,3.0,786,29.786642,-95.390899
9,Georgia,800,+200,26.0,3.0,774,33.762909,-84.422675
10,Massachusetts,777,+131,9.0,4.0,767,42.338551,-71.018253
11,Colorado,720,+129,7.0,1.0,713,39.76185,-104.881105
12,Pennsylvania,644,+165,6.0,3.0,638,40.009376,-75.133346
13,Tennessee,615,+110,2.0,NaN,613,36.1718,-86.785002
14,Ohio,442,+91,6.0,3.0,436,39.984371,-82.984787
15,Wisconsin,416,+35,5.0,1.0,410,43.063348,-87.966695
16,Connecticut,415,+192,10.0,5.0,405,41.187393,-73.195757
17,North Carolina,410,+139,NaN,NaN,410,35.208707,-80.830739
18,South Carolina,299,+104,5.0,2.0,294,32.81793,-79.95896
19,Maryland,288,+44,3.0,NaN,281,39.300032,-76.610476
20,Indiana,259,+58,7.0,1.0,252,39.776664,-86.145935
21,Utah,257,+76,1.0,NaN,256,40.776928,-111.930991
22,Virginia,254,+35,7.0,4.0,246,36.779985,-76.025209
23,Mississippi,249,+42,1.0,NaN,248,32.315831,-90.212823
24,Nevada,245,+55,4.0,2.0,241,36.227551,-115.263782
25,Minnesota,235,+66,1.0,NaN,210,44.963324,-93.26832
26,Arizona,234,+82,2.0,NaN,231,33.572154,-112.090132
27,Arkansas,197,+32,NaN,NaN,197,34.725432,-92.358556
28,Alabama,196,+39,NaN,NaN,196,33.527444,-86.799047
29,Oregon,191,+30,5.0,1.0,186,45.536951,-122.649971
30,Missouri,183,+93,4.0,1.0,179,39.125129,-94.551028
31,District of Columbia,137,+39,2.0,NaN,135,38.904103,-77.017229
32,Kentucky,124,+21,4.0,1.0,118,38.165376,-85.647377
33,Maine,107,+18,NaN,NaN,104,NaN,NaN
34,Rhode Island,106,+23,NaN,NaN,106,41.823056,-71.418784
35,Iowa,105,+15,NaN,NaN,105,41.57259,-93.610243
36,New Hampshire,101,+23,1.0,1.0,100,NaN,NaN
37,New Mexico,83,+18,NaN,NaN,83,35.10478,-106.646809
38,Kansas,82,+18,2.0,NaN,80,37.690638,-97.345836
39,Oklahoma,81,+14,2.0,NaN,78,35.467079,-97.513657
40,Hawaii,77,+21,NaN,NaN,77,21.324347,-157.84764
41,Vermont,75,+23,5.0,3.0,70,NaN,NaN
42,Delaware,68,+12,NaN,NaN,68,NaN,NaN
43,Nebraska,50,+8,NaN,NaN,50,41.261748,-96.047142
44,Idaho,47,+5,NaN,NaN,47,43.600229,-116.231656
45,Montana,45,+11,NaN,NaN,45,NaN,NaN
46,Alaska,32,+10,NaN,NaN,32,61.17425,-149.284329
47,North Dakota,32,+2,NaN,NaN,32,NaN,NaN
48,South Dakota,28,+7,1.0,NaN,21,43.539466,-96.732035
49,Wyoming,26,+2,NaN,NaN,26,NaN,NaN
50,West Virginia,16,+4,NaN,NaN,16,NaN,NaN
51,Diamond Princess Cruise,49,NaN,NaN,NaN,49,NaN,NaN
52,Grand Princess Cruise,30,NaN,1.0,NaN,29,NaN,NaN
53,Total:,43718,10152,552.0,139.0,42871,NaN,NaN

In [13]:
df_final.to_csv('latlng.csv')